<?php

namespace NextDeveloper\CRM\Services;

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use NextDeveloper\CRM\Database\Filters\CallsQueryFilter;
use NextDeveloper\CRM\Services\AbstractServices\AbstractCallsService;

/**
 * This class is responsible from managing the data for Calls
 *
 * Class CallsService.
 *
 * @package NextDeveloper\CRM\Database\Models
 */
class CallsService extends AbstractCallsService
{

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE
    public static function get(CallsQueryFilter $filter = null, array $params = []): Collection|LengthAwarePaginator
    {
        return parent::get($filter, $params); // TODO: Change the autogenerated stub
    }
}
