<?php

namespace NextDeveloper\CRM\Services;

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use NextDeveloper\CRM\Database\Filters\OpportunitiesPerspectiveQueryFilter;
use NextDeveloper\CRM\Services\AbstractServices\AbstractOpportunitiesPerspectiveService;

/**
 * This class is responsible from managing the data for OpportunitiesPerspective
 *
 * Class OpportunitiesPerspectiveService.
 *
 * @package NextDeveloper\CRM\Database\Models
 */
class OpportunitiesPerspectiveService extends AbstractOpportunitiesPerspectiveService
{

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE

    public static function get(OpportunitiesPerspectiveQueryFilter $filter = null, array $params = []): Collection|LengthAwarePaginator
    {
        return parent::get($filter, $params); // TODO: Change the autogenerated stub
    }
}
